### ISSUE TITLE
pawnpin optimization

### ISSUE THREAD

**Issue by rparvat** [Detry322/leiserchess#17]
given a laser path, there are fast ways to check if a move intersects the old laser path (and therefore has a chance to modify the pawnpin heuristic). 
part 1: create a function that checks if a given move has changed the path between two given points. Say we want to see if the old laser segment between (x0,y0) and (x0,y1) has been changed. Just look at the sub-bitarray in row x0, between [y0+1, y1-1]. If the __builtin_popcount for this segment is different before and after the move, then we know this laser segment has been impacted.
part 2: use the between function to check if a given move has impacted laser path at all, and therefore has a chance to change pawnpin and h_squares_attackable heuristics.

**Comment by Detry322** [comment]
Pretty sure we did this
