### ISSUE TITLE
laser path utilization

### ISSUE THREAD

**Issue by rparvat** [Detry322/leiserchess#19]
let's say you have a linked list of pawns in the laser path. Then for any pawn not in the laser path, you can rotate it and not recompute the laser path (or h_squares_attackable). Additionally, for anything in the laser path, if you rotate the laser in 2 of the 3 possible directions, then you know that the laser path will end at that pawn (with that pawn being zapped). To figure out the directions fast, you'd have to store the direction the laser is traveling in during each segment (which is not hard).

**Comment by Detry322** [comment]
We tried this but it was eh
